# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 111f7d512dfb9b4027ebc1001884af22965bc80552d0500a944a45699e5bebf042a70af1e2777c8ce544cc076f67a0b1f784bed08b33a2efca8f59653d746c87

test:
  secret_key_base: ba8d97d99595133440a297592a186b0ac2134e88ea9b8349488136d6860fc7c5bfcdc26e45f1317d609b4ee57ff8d3c163cbb1e376bb03f927e1403edaebcf32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
